title: Reproduction and Additional Results

author: Alexander Daichendt

description: >-
  Applicability of Hardware-Supported Containers in Low-Latency Networking
baseurl: "/applicability-hwsupported-containers" # the subpath of your site, e.g. /blog
url: "https://tumi8.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: tumi8

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-inline-svg

svg:
  optimize: true